[package]
name = "linear_programming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rational = {path = "../rational"}
termion = "1.5.6"

[[bin]]
name = "simplex"
path = "src/simplex.rs"
